QUERY_RESULT_FOLDER=$1
QUERY_FILE=$2
TOOL_FOLDER=$3
INDEX_FOLDER=$4

mkdir $QUERY_RESULT_FOLDER


# bqf
BQF_BIN=$TOOL_FOLDER/bqf/build/bin/bqf
BQF_INDEX_FOLDER=$INDEX_FOLDER/BQF
BQF_INDEXES=$(ls $BQF_INDEX_FOLDER)
BQF_QUERY_FOLDER=$QUERY_RESULT_FOLDER/bqf

mkdir $BQF_QUERY_FOLDER
for INDEX in $BQF_INDEXES; do
    BASENAME=$(basename "$INDEX")
    $BQF_BIN query -b $BQF_INDEX_FOLDER/$INDEX -i $QUERY_FILE -o $BQF_QUERY_FOLDER/$BASENAME.txt
done


# GGCAT
GGCAT_INDEX=$INDEX_FOLDER/ggcat

ggcat query --colors -k 31 -j 1 $GGCAT_INDEX/ggcat_index.fasta $QUERY_FILE # outputs to output.jsonl
mv output.jsonl $QUERY_RESULT_FOLDER/ggcat.jsonl


# kmindex
KMINDEX_INDEX=$INDEX_FOLDER/kmindex

kmindex query -i $KMINDEX_INDEX/G -q $QUERY_FILE -z 6 -o $QUERY_RESULT_FOLDER/kmindex -f json


# Neelde
NEEDLE_BIN=$TOOL_FOLDER/needle/build-needle/bin/needle

$NEEDLE_BIN estimate $QUERY_FILE -i $INDEX_FOLDER/needle/needle.index -o $QUERY_RESULT_FOLDER/needle.out


# REINDEER
REINDEER_BIN=$TOOL_FOLDER/REINDEER/Reindeer

$REINDEER_BIN --query -q $QUERY_FILE  -l $INDEX_FOLDER/REINDEER -o $QUERY_RESULT_FOLDER/reindeer.txt

# Squeakr
SQUEAKR_BIN=$TOOL_FOLDER/squeakr/squeakr
SQUEAKR_INDEX_FOLDER=$INDEX_FOLDER/squeakr
SQUEAKR_INDEXES=$(ls $SQUEAKR_INDEX_FOLDER)
SQUEAKR_QUERY_FOLDER=$QUERY_RESULT_FOLDER/squeakr


mkdir $SQUEAKR_QUERY_FOLDER
for INDEX in $SQUEAKR_INDEXES; do
    BASENAME=$(basename "$INDEX")
    $SQUEAKR_BIN query -f $SQUEAKR_INDEX_FOLDER/$INDEX -q $QUERY_FILE -o $SQUEAKR_QUERY_FOLDER/$BASENAME.output
done

# SSHash
SSHASH_BIN=$TOOL_FOLDER/sshash/build/sshash
SSHASH_INDEX_FOLDER=$INDEX_FOLDER/sshash
SSHASH_QUERY_FOLDER=$QUERY_RESULT_FOLDER/sshash

mkdir -p $SSHASH_QUERY_FOLDER
SSHASH_INDEXES=$(ls $SSHASH_INDEX_FOLDER)

for INDEX in $SSHASH_INDEXES; do
    BASENAME=$(basename "$INDEX")
    $SSHASH_BIN query -i $SSHASH_INDEX_FOLDER/$INDEX -q $QUERY_FILE > $SSHASH_QUERY_FOLDER/$BASENAME.txt
done
